In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

pd.set_option("display.max_columns", 100)

In [11]:
df = pd.read_csv('../../data/train.csv', delimiter=",")
df.head()

,event_id,num_perimeters_0_5h,dt_first_last_0_5h,low_temporal_resolution_0_5h,area_first_ha,area_growth_abs_0_5h,area_growth_rel_0_5h,area_growth_rate_ha_per_h,log1p_area_first,log1p_growth,log_area_ratio_0_5h,relative_growth_0_5h,radial_growth_m,radial_growth_rate_m_per_h,centroid_displacement_m,centroid_speed_m_per_h,spread_bearing_deg,spread_bearing_sin,spread_bearing_cos,dist_min_ci_0_5h,dist_std_ci_0_5h,dist_change_ci_0_5h,dist_slope_ci_0_5h,closing_speed_m_per_h,closing_speed_abs_m_per_h,projected_advance_m,dist_accel_m_per_h2,dist_fit_r2_0_5h,alignment_cos,alignment_abs,cross_track_component,along_track_speed,event_start_hour,event_start_dayofweek,event_start_month,time_to_hit_hours,event
0,10892457,3,4.265188,0,79.696304,2.875935,0.036086,0.674281,4.390693,1.354787,0.03545,0.036086,9.007182,2.11179,8.274971,1.940119,70.130507,0.940469,0.339879,6166.121596,0.205085,0.435052,1.090997e-01,-0.102001,0.102001,-0.435052,7.275611e-02,0.886373,-0.054649,0.054649,-1.937219,-0.106026,19,4,5,18.892512,0
1,11757157,2,1.169918,0,8.946749,0.000000,0.000000,0.000000,2.297246,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,2930.925956,0.000000,0.000000,-3.887003e-13,0.000000,0.000000,0.000000,0.000000e+00,0.000000,-0.568898,0.568898,-0.000000,-0.000000,4,4,6,22.048108,1
2,11945086,4,4.777526,0,106.482638,0.000000,0.000000,0.000000,4.677329,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,3272.375090,0.000000,0.000000,-1.390327e-13,0.000000,0.000000,0.000000,7.965118e-14,0.000000,0.882385,0.882385,0.000000,0.000000,22,4,8,0.888895,1
3,12044083,1,0.000000,1,67.631125,0.000000,0.000000,0.000000,4.228746,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,64119.871377,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,20,5,8,60.953021,0
4,12052347,2,4.975273,0,35.632874,0.000000,0.000000,0.000000,3.600946,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,18005.432261,0.000000,0.000000,3.656059e-13,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.934634,0.934634,-0.000000,0.000000,21,5,7,44.990274,0

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   event_id                      221 non-null    int64
 1   num_perimeters_0_5h           221 non-null    int64
 2   dt_first_last_0_5h            221 non-null    float64
 3   low_temporal_resolution_0_5h  221 non-null    int64
 4   area_first_ha                 221 non-null    float64
 5   area_growth_abs_0_5h          221 non-null    float64
 6   area_growth_rel_0_5h          221 non-null    float64
 7   area_growth_rate_ha_per_h     221 non-null    float64
 8   log1p_area_first              221 non-null    float64
 9   log1p_growth                  221 non-null    float64
 10  log_area_ratio_0_5h           221 non-null    float64
 11  relative_growth_0_5h          221 non-null    float64
 12  radial_growth_m               221 non-null    float64
 13  radial_growth_rate_m_per_h    221 non-null    float64
 14  centroid_displacement_m       221 non-null    float64
 15  centroid_speed_m_per_h        221 non-null    float64
 16  spread_bearing_deg            221 non-null    float64
 17  spread_bearing_sin            221 non-null    float64
 18  spread_bearing_cos            221 non-null    float64
 19  dist_min_ci_0_5h              221 non-null    float64
 20  dist_std_ci_0_5h              221 non-null    float64
 21  dist_change_ci_0_5h           221 non-null    float64
 22  dist_slope_ci_0_5h            221 non-null    float64
 23  closing_speed_m_per_h         221 non-null    float64
 24  closing_speed_abs_m_per_h     221 non-null    float64
 25  projected_advance_m           221 non-null    float64
 26  dist_accel_m_per_h2           221 non-null    float64
 27  dist_fit_r2_0_5h              221 non-null    float64
 28  alignment_cos                 221 non-null    float64
 29  alignment_abs                 221 non-null    float64
 30  cross_track_component         221 non-null    float64
 31  along_track_speed             221 non-null    float64
 32  event_start_hour              221 non-null    int64
 33  event_start_dayofweek         221 non-null    int64
 34  event_start_month             221 non-null    int64
 35  time_to_hit_hours             221 non-null    float64
 36  event                         221 non-null    int64
dtypes: float64(30), int64(7)
memory usage: 64.0 KB

In [13]:
df.shape

(221, 37)

In [14]:
print(df.columns)

Index(['event_id', 'num_perimeters_0_5h', 'dt_first_last_0_5h',
       'low_temporal_resolution_0_5h', 'area_first_ha', 'area_growth_abs_0_5h',
       'area_growth_rel_0_5h', 'area_growth_rate_ha_per_h', 'log1p_area_first',
       'log1p_growth', 'log_area_ratio_0_5h', 'relative_growth_0_5h',
       'radial_growth_m', 'radial_growth_rate_m_per_h',
       'centroid_displacement_m', 'centroid_speed_m_per_h',
       'spread_bearing_deg', 'spread_bearing_sin', 'spread_bearing_cos',
       'dist_min_ci_0_5h', 'dist_std_ci_0_5h', 'dist_change_ci_0_5h',
       'dist_slope_ci_0_5h', 'closing_speed_m_per_h',
       'closing_speed_abs_m_per_h', 'projected_advance_m',
       'dist_accel_m_per_h2', 'dist_fit_r2_0_5h', 'alignment_cos',
       'alignment_abs', 'cross_track_component', 'along_track_speed',
       'event_start_hour', 'event_start_dayofweek', 'event_start_month',
       'time_to_hit_hours', 'event'],
      dtype='str')

In [15]:
df.isna().sum()

event_id                        0
num_perimeters_0_5h             0
dt_first_last_0_5h              0
low_temporal_resolution_0_5h    0
area_first_ha                   0
area_growth_abs_0_5h            0
area_growth_rel_0_5h            0
area_growth_rate_ha_per_h       0
log1p_area_first                0
log1p_growth                    0
log_area_ratio_0_5h             0
relative_growth_0_5h            0
radial_growth_m                 0
radial_growth_rate_m_per_h      0
centroid_displacement_m         0
centroid_speed_m_per_h          0
spread_bearing_deg              0
spread_bearing_sin              0
spread_bearing_cos              0
dist_min_ci_0_5h                0
dist_std_ci_0_5h                0
dist_change_ci_0_5h             0
dist_slope_ci_0_5h              0
closing_speed_m_per_h           0
closing_speed_abs_m_per_h       0
projected_advance_m             0
dist_accel_m_per_h2             0
dist_fit_r2_0_5h                0
alignment_cos                   0
alignment_abs                   0
cross_track_component           0
along_track_speed               0
event_start_hour                0
event_start_dayofweek           0
event_start_month               0
time_to_hit_hours               0
event                           0
dtype: int64

In [16]:
df.head(10)

,event_id,num_perimeters_0_5h,dt_first_last_0_5h,low_temporal_resolution_0_5h,area_first_ha,area_growth_abs_0_5h,area_growth_rel_0_5h,area_growth_rate_ha_per_h,log1p_area_first,log1p_growth,log_area_ratio_0_5h,relative_growth_0_5h,radial_growth_m,radial_growth_rate_m_per_h,centroid_displacement_m,centroid_speed_m_per_h,spread_bearing_deg,spread_bearing_sin,spread_bearing_cos,dist_min_ci_0_5h,dist_std_ci_0_5h,dist_change_ci_0_5h,dist_slope_ci_0_5h,closing_speed_m_per_h,closing_speed_abs_m_per_h,projected_advance_m,dist_accel_m_per_h2,dist_fit_r2_0_5h,alignment_cos,alignment_abs,cross_track_component,along_track_speed,event_start_hour,event_start_dayofweek,event_start_month,time_to_hit_hours,event
0,10892457,3,4.265188,0,79.696304,2.875935,0.036086,0.674281,4.390693,1.354787,0.03545,0.036086,9.007182,2.11179,8.274971,1.940119,70.130507,0.940469,0.339879,6166.121596,0.205085,0.435052,1.090997e-01,-0.102001,0.102001,-0.435052,7.275611e-02,0.886373,-0.054649,0.054649,-1.937219,-0.106026,19,4,5,18.892512,0
1,11757157,2,1.169918,0,8.946749,0.000000,0.000000,0.000000,2.297246,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,2930.925956,0.000000,0.000000,-3.887003e-13,0.000000,0.000000,0.000000,0.000000e+00,0.000000,-0.568898,0.568898,-0.000000,-0.000000,4,4,6,22.048108,1
2,11945086,4,4.777526,0,106.482638,0.000000,0.000000,0.000000,4.677329,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,3272.375090,0.000000,0.000000,-1.390327e-13,0.000000,0.000000,0.000000,7.965118e-14,0.000000,0.882385,0.882385,0.000000,0.000000,22,4,8,0.888895,1
3,12044083,1,0.000000,1,67.631125,0.000000,0.000000,0.000000,4.228746,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,64119.871377,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,20,5,8,60.953021,0
4,12052347,2,4.975273,0,35.632874,0.000000,0.000000,0.000000,3.600946,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,18005.432261,0.000000,0.000000,3.656059e-13,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.934634,0.934634,-0.000000,0.000000,21,5,7,44.990274,0
5,12773599,1,0.000000,1,184.767610,0.000000,0.000000,0.000000,5.224496,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,35232.562968,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0,5,7,44.026384,0
6,13122360,1,0.000000,1,119.364203,0.000000,0.000000,0.000000,4.790522,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,3530.472886,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,21,1,3,14.845392,1
7,13745272,1,0.000000,1,1388.283778,0.000000,0.000000,0.000000,7.236544,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,8038.691359,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,16,0,6,66.767927,0
8,15247236,2,1.892776,0,4.493970,0.000000,0.000000,0.000000,1.703651,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,31758.581144,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.106322,0.106322,0.000000,0.000000,18,5,8,39.912630,0
9,15743535,1,0.000000,1,5.218524,0.000000,0.000000,0.000000,1.827533,0.000000,0.00000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,1995.042356,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,17,2,7,54.638109,1

In [17]:
df.tail(10)

,event_id,num_perimeters_0_5h,dt_first_last_0_5h,low_temporal_resolution_0_5h,area_first_ha,area_growth_abs_0_5h,area_growth_rel_0_5h,area_growth_rate_ha_per_h,log1p_area_first,log1p_growth,log_area_ratio_0_5h,relative_growth_0_5h,radial_growth_m,radial_growth_rate_m_per_h,centroid_displacement_m,centroid_speed_m_per_h,spread_bearing_deg,spread_bearing_sin,spread_bearing_cos,dist_min_ci_0_5h,dist_std_ci_0_5h,dist_change_ci_0_5h,dist_slope_ci_0_5h,closing_speed_m_per_h,closing_speed_abs_m_per_h,projected_advance_m,dist_accel_m_per_h2,dist_fit_r2_0_5h,alignment_cos,alignment_abs,cross_track_component,along_track_speed,event_start_hour,event_start_dayofweek,event_start_month,time_to_hit_hours,event
211,94424495,1,0.000000,1,6.536042,0.0,0.0,0.0,2.019697,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,7509.221711,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.0,0.0,0,1,7,18.706878,0
212,94488511,5,4.921366,0,2.374141,0.0,0.0,0.0,1.216141,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,209573.726705,0.0,0.0,3.123089e-11,0.0,0.0,0.0,-5.289689e-12,0.0,-0.999990,0.999990,-0.0,-0.0,16,0,9,64.782509,0
213,95839532,1,0.000000,1,42.287223,0.0,0.0,0.0,3.767858,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,5639.409208,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.0,0.0,23,1,8,66.094550,0
214,96270286,1,0.000000,1,3403.021842,0.0,0.0,0.0,8.132713,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,196116.778672,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.0,0.0,20,1,7,65.012587,0
215,96372213,1,0.000000,1,169.688297,0.0,0.0,0.0,5.139839,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,325976.711111,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.0,0.0,21,0,6,43.109830,0
216,97075632,1,0.000000,1,51.295195,0.0,0.0,0.0,3.956904,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,280232.192858,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.0,0.0,17,6,6,66.340624,0
217,97362560,2,1.127102,0,1.176991,0.0,0.0,0.0,0.777943,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4544.949069,0.0,0.0,-1.210398e-12,0.0,0.0,0.0,0.000000e+00,0.0,-0.277779,0.277779,-0.0,-0.0,18,1,7,5.694898,1
218,97805715,2,3.710653,0,71.946930,0.0,0.0,0.0,4.289732,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,6031.675383,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.694609,0.694609,0.0,0.0,18,1,9,44.011253,0
219,99071478,1,0.000000,1,20.223659,0.0,0.0,0.0,3.055117,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4673.854411,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.0,0.0,15,0,8,22.975783,1
220,99339733,1,0.000000,1,902.231688,0.0,0.0,0.0,6.805979,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,319890.135556,0.0,0.0,0.000000e+00,0.0,0.0,0.0,0.000000e+00,0.0,0.000000,0.000000,0.0,0.0,21,1,7,0.617344,0

In [21]:
train, val = train_test_split(df, test_size=0.1, shuffle=True, random_state=42)

print(train.shape)
print(val.shape)

(198, 37)
(23, 37)

In [22]:
train.to_csv("../../data/train.csv", index = False)
val.to_csv("../../data/val.csv", index = False)